### PR TITLE
Piwik Plugin update for compatibilty with mantisbt >2.0

### PR DESCRIPTION
**Pull request by FSD-Christian-ADM**
- changed the config page with new layout functions
- outsourced inline JS to seperate file
- added custom headers to allow external JS from piwik server

### CODE REVIEW

**Comment by fred-the-coder** [comment]
Hi Christian, 
Thanks for updating this plugin to work with mantis>2.0
Are you done now?
Cheers

**Comment by FSD-Christian-ADM** [comment]
Hi Fred,

I’m done with updating this plugin, I guess.
I tested it with a MantisBT 2.2.1 environment.

Regards,
Christian



Von: fred-the-coder [mailto:notifications@github.com]
Gesendet: Donnerstag, 20. April 2017 18:06
An: mantisbt-plugins/piwik <piwik@noreply.github.com>
Cc: Schulz, Christian <Christian.Schulz@fsd-web.de>; Author <author@noreply.github.com>
Betreff: Re: [mantisbt-plugins/piwik] Piwik Plugin update for compatibilty with mantisbt >2.0 (#1)


Hi Christian,
Thanks for updating this plugin to work with mantis>2.0
Are you done now?
Cheers

**Comment by fred-the-coder** [comment]
OK,
Thanks for your answer and for sharing your code!
Have a nice day

**Review by dregad — APPROVED** [review]
I do not use this plugin, so I'll just assume that you've properly tested the proposed changes and merge the PR as is.

**Pull request merged**
